#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Seed theme keyword seeds (e.g. Halloween) into the category index / local YAML.

基于 config/themes.yaml 的主题关键词表，生成 AliExpress 批发搜索 seeds
（/w/wholesale-<keyword>.html，自动附加 maxPrice / 星级 / SortType 过滤）：

  - 默认       ：upsert 到 ELASTICSEARCH_INDEX_CATEGORIES（claim 模式下现有循环每轮自动抓取）
  - --no-es    ：只写本地 categories.<theme>.yaml + data JSONL（配合 CATEGORIES_FILE= 使用）
  - --list     ：只打印将生成的 keyword -> URL，不做任何写入
  - --clean    ：从 ES 删除该主题的全部 seeds（节日结束后一键清理，需配合 --no-es 不可同时用）

用法:
  .venv/bin/python seed_theme_keywords.py --list
  .venv/bin/python seed_theme_keywords.py
  .venv/bin/python seed_theme_keywords.py --only halloween
  .venv/bin/python seed_theme_keywords.py --no-es --yaml-out config/categories.halloween.yaml
  .venv/bin/python seed_theme_keywords.py --clean

退出码: 0=成功（clean 删除 0 条也算成功）
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

from alilj import (
    BASE_DIR,
    build_claim_client,
    is_blacklisted_category,
    utc_now_iso,
    wholesale_slug,
    wholesale_search_url,
)

DEFAULT_THEMES_FILE = BASE_DIR / "config" / "themes.yaml"
DEFAULT_YAML_DIR = BASE_DIR / "config"
DEFAULT_JSONL_DIR = BASE_DIR / "data"
THEME_SEED_TYPE = "theme_keyword"
SITE_BASES = {
    "us": "https://www.aliexpress.us",
    "com": "https://www.aliexpress.com",
}


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate theme keyword seeds (wholesale search URLs) → ES / local files."
    )
    parser.add_argument(
        "--themes-file",
        type=Path,
        default=None,
        help="Theme keyword table (default: config/themes.yaml)",
    )
    parser.add_argument(
        "--only",
        default=None,
        help="Only process a theme by name (case-insensitive, e.g. --only halloween)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print keyword -> URL preview only; no writes",
    )
    parser.add_argument(
        "--no-es",
        action="store_true",
        help="Do not write to Elasticsearch; write local YAML + JSONL instead",
    )
    parser.add_argument(
        "--yaml-out",
        type=Path,
        default=None,
        help="Local L1-style YAML path (default: config/categories.<theme>.yaml)",
    )
    parser.add_argument(
        "--jsonl-out",
        type=Path,
        default=None,
        help="Local JSONL backup path (default: data/theme_seeds.<theme>.jsonl)",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete all seeds of this theme from ES (season cleanup)",
    )
    return parser.parse_args(argv)


def load_themes(path: Path) -> list[dict]:
    if not path.exists():
        print(f"主题关键词表不存在: {path}")
        sys.exit(2)
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    themes = [t for t in (raw.get("themes") or []) if isinstance(t, dict)]
    if not themes:
        print(f"主题关键词表为空（缺 themes 列表）: {path}")
        sys.exit(2)
    return themes


def build_seed_docs(
    theme: dict,
    *,
    site_base: str,
) -> list[dict]:
    """Keyword list -> ES seed docs (wholesale search URLs)."""
    name = str(theme.get("name") or "").strip()
    keywords = [str(k).strip() for k in (theme.get("keywords") or []) if str(k).strip()]
    docs: list[dict] = []
    base_priority = int(theme.get("priority_base") or 9900000)
    for i, keyword in enumerate(keywords):
        if is_blacklisted_category(name=keyword):
            print(f"  跳过黑名单关键词: {keyword}")
            continue
        slug = wholesale_slug(keyword)
        row = {
            "name": f"Theme / {name} > {slug}",
            "display_name": keyword,
            "url": wholesale_search_url(keyword, site_base),
            "parent_name": f"Theme / {name}",
            "seed_type": THEME_SEED_TYPE,
            "theme": name.lower(),
            "enabled": True,
            "priority": base_priority + i + 1,
            "site": "us" if "aliexpress.us" in site_base else "com",
            "created_by": "seed_theme_keywords",
            "updated_at": utc_now_iso(),
        }
        docs.append(row)
    return docs


def write_local_files(
    docs: list[dict],
    *,
    theme_name: str,
    yaml_out: Path,
    jsonl_out: Path,
) -> None:
    yaml_out.parent.mkdir(parents=True, exist_ok=True)
    jsonl_out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by seed_theme_keywords.py — do not edit by hand.",
        f"# Theme: {theme_name} — wholesale search seeds. Generated at {utc_now_iso()}",
        "# Use with CATEGORIES_FILE=<this file> (claim mode: off) or merge into ES.",
        "categories:",
    ]
    for doc in docs:
        lines.append(f"  - name: {doc['name']}")
        lines.append(f"    url: {doc['url']}")
        lines.append("")
    yaml_out.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    with jsonl_out.open("w", encoding="utf-8") as fh:
        for doc in docs:
            fh.write(json.dumps(doc, ensure_ascii=False) + "\n")
    print(f"已写 YAML : {yaml_out}（{len(docs)} 条）")
    print(f"已写 JSONL: {jsonl_out}（{len(docs)} 条）")


def clean_theme_from_es(claim_client, *, theme: str) -> int:
    """Delete theme seeds from ES; returns number of deleted docs."""
    if claim_client is None or claim_client.client is None:
        print("未配置 ES 类别索引（CATEGORY_CLAIM_MODE / ELASTICSEARCH_INDEX_CATEGORIES），无法清理。")
        return 0
    query = {
        "bool": {
            "must": [
                {"term": {"seed_type.keyword": THEME_SEED_TYPE}},
                {"term": {"theme": theme.lower()}},
            ]
        }
    }
    resp = claim_client.client.delete_by_query(
        index=claim_client.index,
        body={"query": query},
        refresh=True,
        conflicts="proceed",
    )
    n = int(resp.get("deleted") or 0)
    print(f"[clean] 已删除 theme={theme!r} 的 seeds: {n} 条")
    return n


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    if args.clean and args.no_es:
        print("--clean 与 --no-es 不能同时使用。")
        sys.exit(2)

    themes_file = args.themes_file or DEFAULT_THEMES_FILE
    themes = load_themes(themes_file)
    if args.only:
        wanted = args.only.strip().lower()
        themes = [t for t in themes if str(t.get("name") or "").strip().lower() == wanted]
        if not themes:
            print(f"未找到主题: {args.only}")
            sys.exit(2)

    # ---- clean 模式：不动本地文件，只删 ES ----
    if args.clean:
        claim_client = build_claim_client()
        total = 0
        for theme in themes:
            total += clean_theme_from_es(claim_client, theme=str(theme.get("name") or ""))
        print(f"清理完成，共删除 {total} 条主题 seeds。")
        return

    all_docs: list[dict] = []
    for theme in themes:
        name = str(theme.get("name") or "").strip()
        if not theme.get("enabled", True) and not args.only:
            theme_tag = name.lower()
            if theme_tag not in {"halloween", "christmas"}:
                # 未启用的主题默认跳过（除非 --only 明确指定）。
                print(f"跳过未启用主题: {name}（用 --only {name} 强制处理）")
                continue
        site_base = SITE_BASES.get(
            str(theme.get("site") or "us").strip().lower(), SITE_BASES["us"]
        )
        docs = build_seed_docs(theme, site_base=site_base)
        if not docs:
            print(f"主题 {name}: 无可生成 seeds（全部被黑名单过滤？）")
            continue
        print(f"\n主题: {name}（{len(docs)} 个关键词 seeds）")
        if args.list:
            for doc in docs:
                print(f"  {doc['display_name']:35s} -> {doc['url']}")
            continue
        all_docs.extend(docs)

    # ---- 预览结束 ----
    if args.list:
        return

    if not args.no_es:
        claim_client = build_claim_client()
        if claim_client is None:
            print(
                "未配置 claim 模式（CATEGORY_CLAIM_MODE=1 且 ELASTICSEARCH_INDEX_CATEGORIES 非空）。"
                "\n请改用 --no-es 生成本地 yaml，或检查 .env。"
            )
            sys.exit(1)
        total = 0
        for theme in themes:
            name = str(theme.get("name") or "").strip()
            site_base = SITE_BASES.get(
                str(theme.get("site") or "us").strip().lower(), SITE_BASES["us"]
            )
            docs = build_seed_docs(theme, site_base=site_base)
            if not docs:
                continue
            n = claim_client.upsert_seeds(docs)
            total += n
            print(f"[es] 主题 {name}: upsert {n}/{len(docs)} seeds -> {claim_client.index}")
        print(f"ES 总 seed 数（enabled）: {claim_client.count_enabled_seeds()}")
        return

    # ---- 本地文件模式 ----
    # 按主题分别输出 yaml/jsonl（文件名含主题名）。
    for theme in themes:
        name = str(theme.get("name") or "").strip()
        site_base = SITE_BASES.get(
            str(theme.get("site") or "us").strip().lower(), SITE_BASES["us"]
        )
        docs = build_seed_docs(theme, site_base=site_base)
        if not docs:
            continue
        safe = wholesale_slug(name)
        yaml_out = args.yaml_out or (DEFAULT_YAML_DIR / f"categories.{safe}.yaml")
        jsonl_out = args.jsonl_out or (DEFAULT_JSONL_DIR / f"theme_seeds.{safe}.jsonl")
        write_local_files(docs, theme_name=name, yaml_out=yaml_out, jsonl_out=jsonl_out)


if __name__ == "__main__":
    main(sys.argv[1:])